### ISSUE TITLE
[BUG][DOCS] new undocumented `tft-match-v1` fields: `InfoDto.tft_game_type/tft_set_core_name/endOfGameResult/gameCreation/gameId/mapId/queueId`, `ParticipantDto.augments/partner_group_id/missions/win/skill_tree`, `Companion.item_ID`, `UnitDto.itemNames`

### ISSUE THREAD

**Issue by MingweiSamuel** [RiotGames/developer-relations#749]
Missing from docs:
* `tft-match-v1.InfoDto.tft_game_type`: `String`
* `tft-match-v1.InfoDto.tft_set_core_name`: `String`
* `tft-match-v4.InfoDto.endOfGameResult`: `String` (2024-02-16) #890
* `tft-match-v1.InfoDto.gameCreation`: `long integer` (2024-03-13)
* `tft-match-v1.InfoDto.gameId`: `integer` (2024-03-13)
* `tft-match-v1.InfoDto.mapId`: `integer` (2024-03-13)
* `tft-match-v1.InfoDto.queueId`: `integer` (2024-03-13)
* `tft-match-v1.ParticipantDto.augments`: `List[String]`
* `tft-match-v1.ParticipantDto.partner_group_id`: `integer`
* `tft-match-v1.ParticipantDto.missions`: `ParticipantMissionsDto` (undocumented) (2024-03-13)
* `tft-match-v1.Companion.item_ID`: `integer`
* `tft-match-v1.UnitDto.itemNames`: `List[String]`

`ParticipantMissionsDto`: (39 fields, all positive integers?)
```yaml
Assists: 15
DamageDealt: 0
DamageDealtToObjectives: 1
DamageDealtToTurrets: 1
DamageTaken: 19
DoubleKills: 3
GoldEarned: 68
GoldSpent: 51
InhibitorsDestroyed: 0
Kills: 0
LargestKillingSpree: 1
LargestMultiKill: 5
MagicDamageDealt: 8
MagicDamageDealtToChampions: 16
NeutralMinionsKilledTeamJungle: 14
PhysicalDamageDealt: 8
PhysicalDamageTaken: 0
PlayerScore0: 1
PlayerScore1: 0
PlayerScore10: 354339
PlayerScore11: 7
PlayerScore2: 209
PlayerScore3: 150
PlayerScore4: 3
PlayerScore5: 5
PlayerScore6: 11
PlayerScore9: 45
QuadraKills: 10
Spell1Casts: 68728
Spell2Casts: 0
Spell3Casts: 0
Spell4Casts: 37
SummonerSpell1Casts: 37
TimeCCOthers: 1
TotalMinionsKilled: 9
TrueDamageDealtToChampions: 0
UnrealKills: 11
VisionScore: 37045
WardsKilled: 0

# New 2024-03-20:
Deaths: 0
KillingSprees: 0
MagicDamageTaken: 0
"tft-match-v1.ParticipantMissionsDto.MagicDamageTaken": true,
"tft-match-v1.ParticipantMissionsDto.PentaKills": true,
"tft-match-v1.ParticipantMissionsDto.PhysicalDamageDealtToChampions": true,
"tft-match-v1.ParticipantMissionsDto.TotalDamageDealtToChampions": true,
"tft-match-v1.ParticipantMissionsDto.TripleKills": true,
"tft-match-v1.ParticipantMissionsDto.TrueDamageDealt": true,
"tft-match-v1.ParticipantMissionsDto.TrueDamageTaken": true,
```

**Comment by MingweiSamuel** [comment]
New undocumented field `InfoDto.gameCreation` (long int)

**Comment by MingweiSamuel** [comment]
#890 as well

**Comment by MingweiSamuel** [comment]
Wow get both `queueId` and `queue_id` in `tft-match-v1.InfoDto` now, lmao

**Comment by MingweiSamuel** [comment]
Missions new
```yaml
# New 2024-03-20:
Deaths: 0
KillingSprees: 0
```
